# Generated by Django 5.0.4 on 2024-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_status',
            new_name='user_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='live_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
