# Generated by Django 5.0.4 on 2024-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_live_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='indiamartLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(blank=True, max_length=300, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('product', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('enquery_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
