# Generated by Django 5.0.4 on 2024-05-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_indiamartlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiamartlead',
            name='query_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
