# Generated by Django 5.0.4 on 2024-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_indiamartlead_query_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_request', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
