# Generated by Django 5.0.4 on 2024-05-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_last_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='productBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='masterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=400, null=True)),
                ('oem_number', models.CharField(blank=True, max_length=300, null=True)),
                ('part_number', models.CharField(blank=True, max_length=300, null=True)),
                ('length', models.CharField(blank=True, max_length=300, null=True)),
                ('breath', models.CharField(blank=True, max_length=300, null=True)),
                ('height', models.CharField(blank=True, max_length=300, null=True)),
                ('mrp', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=300, null=True)),
                ('material', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productbrand')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producttype')),
            ],
        ),
    ]
