# Generated by Django 5.0.4 on 2024-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_breath_masterproduct_breadth'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
