# Generated by Django 5.0.4 on 2024-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_masterproduct_weight_alter_masterproduct_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiamartlead',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
