# Generated by Django 5.0.4 on 2024-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_indiamartlead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='oem_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='part_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
