# Generated by Django 5.0.4 on 2024-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_masterproduct_oem_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='partsklik_brand',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
