# Generated by Django 5.0.4 on 2024-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_masterproduct_partsklik_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='mrp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
