# Generated by Django 5.0.4 on 2024-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_masterproduct_gst_percent_masterproduct_hsn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.CharField(max_length=300)),
            ],
        ),
    ]
