# Generated by Django 5.0.4 on 2024-05-04 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='block_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 12, 46, 35, 78603)),
        ),
    ]
