# Generated by Django 5.0.4 on 2024-05-04 08:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_masterproduct_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_house', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='masterproduct',
            name='block_number',
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 13, 36, 24, 182842)),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='product_sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.masterproduct')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blocks')),
                ('where_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wherehouses')),
            ],
        ),
    ]
