# Generated by Django 5.0.4 on 2024-05-04 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_masterproduct_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhereHouses',
            new_name='WareHouses',
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 15, 6, 52, 210805)),
        ),
    ]
