# Generated by Django 5.0.4 on 2024-05-04 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_wherehouses_warehouses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouses',
            old_name='where_house',
            new_name='ware_house',
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 15, 29, 41, 942280)),
        ),
    ]
