# Generated by Django 5.0.4 on 2024-05-04 10:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_where_house_warehouses_ware_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 15, 34, 30, 623912)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.racks'),
        ),
        migrations.DeleteModel(
            name='Blocks',
        ),
    ]
