# Generated by Django 5.0.4 on 2024-05-04 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_racks_alter_masterproduct_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='where_house',
            new_name='ware_house',
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 15, 38, 14, 456067)),
        ),
    ]
