# Generated by Django 5.0.4 on 2024-05-04 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_where_house_inventory_ware_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 15, 40, 37, 478146)),
        ),
    ]
